# Generated by Django 2.2.1 on 2019-06-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='myhood_id',
            new_name='myhood',
        ),
    ]
