# Generated by Django 2.2.1 on 2019-06-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190603_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='myhood',
        ),
    ]
