# Generated by Django 2.2.1 on 2019-06-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190603_1848'),
        ('accounts', '0003_remove_profile_myhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hoodid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_hood', to='pages.NeighbourHood'),
        ),
    ]
